"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/context/AuthContext";

export function AdminJsonEditor({ title, endpoint, dataKey, create = false, template = {} }: { title: string; endpoint: string; dataKey: string; create?: boolean; template?: object }) {
  const { authToken } = useAuth(); const router = useRouter();
  const [text, setText] = useState(JSON.stringify(template, null, 2)); const [updatedAt, setUpdatedAt] = useState<string>(); const [message, setMessage] = useState("");
  useEffect(() => { if (create || !authToken) return; void fetch(endpoint, { headers: { Authorization: `Bearer ${authToken}` } }).then((response) => response.json()).then((data) => { const value = data[dataKey]; setUpdatedAt(value?.updatedAt); setText(JSON.stringify(value, null, 2)); }); }, [authToken, create, dataKey, endpoint]);
  async function save() { try { const payload = JSON.parse(text); for (const field of ["id", "createdAt", "updatedAt", "line", "category", "images", "skus", "sections", "pending", "media", "_count"]) delete payload[field]; const response = await fetch(endpoint, { method: create ? "POST" : "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${authToken}`, ...(!create && updatedAt ? { "If-Match": updatedAt } : {}) }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || JSON.stringify(data.fields)); const value = data[dataKey]; setUpdatedAt(value?.updatedAt); setText(JSON.stringify(value, null, 2)); setMessage("Salvo com sucesso."); if (create && value?.id) router.replace(`${location.pathname.replace(/\/novo$/, "")}/${value.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao salvar."); } }
  return <section><p className="font-mono text-xs uppercase tracking-wider text-accent">Editor administrativo</p><h1 className="font-display text-4xl font-semibold">{title}</h1><p className="mt-3 max-w-3xl text-sm text-content/65">Editor estruturado em JSON para todos os campos do catálogo. Validações de publicação, cores, tags, concorrência e tipos continuam aplicadas no servidor.</p><textarea aria-label="Dados do registro" value={text} onChange={(event) => setText(event.target.value)} className="mt-6 min-h-[520px] w-full rounded-2xl border border-content/15 bg-card p-5 font-mono text-xs" spellCheck={false} /><div className="mt-4 flex items-center gap-4"><button type="button" onClick={save} className="rounded-full bg-action px-6 py-3 text-sm font-semibold text-action-fg">Salvar rascunho</button><p role="status" className="text-sm">{message}</p></div></section>;
}
