"use client";
import { useEffect, useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { inputClass, ReorderList } from "./AdminUi";
type Row = Record<string, any>;
export function CategoryManager() { const { authToken } = useAuth(); const [lines, setLines] = useState<Row[]>([]); const [rows, setRows] = useState<Row[]>([]); const [message, setMessage] = useState(""); const headers = { "Content-Type": "application/json", Authorization: `Bearer ${authToken}` };
  const load = () => { if (!authToken) return; void Promise.all([fetch("/api/admin/catalog/lines", { headers }).then((r) => r.json()), fetch("/api/admin/catalog/categories", { headers }).then((r) => r.json())]).then(([lineData, categoryData]) => { setLines(lineData.lines ?? []); setRows(categoryData.categories ?? []); }); };
  useEffect(load, [authToken]);
  async function save(row: Row, create = false) { const response = await fetch(create ? "/api/admin/catalog/categories" : `/api/admin/catalog/categories/${row.id}`, { method: create ? "POST" : "PATCH", headers: { ...headers, ...(!create ? { "If-Match": row.updatedAt } : {}) }, body: JSON.stringify({ lineId: row.lineId || null, name: row.name, slug: row.slug, sortOrder: row.sortOrder }) }); const data = await response.json(); setMessage(response.ok ? "Categoria salva." : data.error || "Falha ao salvar."); if (response.ok) load(); }
  async function remove(row: Row) { const response = await fetch(`/api/admin/catalog/categories/${row.id}`, { method: "DELETE", headers }); const data = await response.json(); setMessage(response.ok ? "Categoria excluída." : data.error || "Falha ao excluir."); if (response.ok) load(); }
  const update = (id: string, patch: Row) => setRows((current) => current.map((row) => row.id === id ? { ...row, ...patch } : row));
  return <section><p className="font-mono text-xs uppercase tracking-wider text-accent">Catálogo</p><div className="flex flex-wrap items-end justify-between gap-3"><h1 className="mt-1 font-display text-4xl font-semibold">Categorias</h1><button type="button" onClick={() => setRows((current) => [...current, { id: `new-${Date.now()}`, lineId: lines[0]?.id || "", name: "", slug: "", sortOrder: current.length, _count: { products: 0 }, isNew: true }])} className="rounded-full bg-action px-5 py-2.5 text-sm font-semibold text-action-fg"><Plus className="mr-1 inline h-4 w-4" />Nova categoria</button></div>
    <div className="mt-7 space-y-7">{lines.map((line) => { const categories = rows.filter((row) => row.lineId === line.id); return <div key={line.id}><h2 className="mb-3 font-display text-xl font-semibold">{line.name}</h2><ReorderList items={categories} onMove={(from, to) => { const next = [...categories]; const [item] = next.splice(from, 1); next.splice(to, 0, item); setRows((current) => [...current.filter((row) => row.lineId !== line.id), ...next.map((row, index) => ({ ...row, sortOrder: index }))]); }} render={(row: Row) => <div className="grid flex-1 gap-2 md:grid-cols-[1fr_1fr_8rem_auto]"><input className={inputClass} value={row.name} placeholder="Nome" onChange={(e) => update(row.id, { name: e.target.value })} /><input className={inputClass} value={row.slug} placeholder="slug" onChange={(e) => update(row.id, { slug: e.target.value })} /><span className="self-center text-xs text-content/55">{row._count?.products ?? 0} produto(s)</span><div className="flex"><button type="button" onClick={() => void save(row, row.isNew)} className="p-2 text-accent" aria-label="Salvar"><Save className="h-4 w-4" /></button>{!row.isNew ? <button type="button" onClick={() => void remove(row)} className="p-2 text-red-600" aria-label="Excluir"><Trash2 className="h-4 w-4" /></button> : null}</div></div>} /></div>; })}</div>{message ? <p className="mt-4 rounded-xl bg-raised p-3 text-sm">{message}</p> : null}
  </section>;
}
