"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/context/AuthContext";
import { AdminField, AdminTabs, inputClass, SaveBar, toSlug } from "./AdminUi";
import { MediaPicker } from "./AdminSelectors";
type Row = Record<string, any>;
const tabs = ["Identidade", "Cores", "Institucional", "Fotos", "Publicação"];
const empty: Row = { slug: "", name: "", descriptor: "", tagline: "", surfaceLight: "#EEF1F5", surfaceDark: "#0F1D30", accentLight: "#B4872D", accentDark: "#D8B657", inkLight: "#12283C", inkDark: "#F7F5F0", mission: "", vision: "", values: "", differentials: [], commitments: [], sortOrder: 0, status: "DRAFT", media: [] };
export function LineAdminForm({ endpoint, create = false }: { endpoint: string; create?: boolean }) { const { authToken } = useAuth(); const router = useRouter(); const [form, setForm] = useState<Row>(empty); const [tab, setTab] = useState(tabs[0]); const [state, setState] = useState<"saved" | "dirty" | "saving" | "conflict">("saved"); const [message, setMessage] = useState(""); const change = (key: string, value: unknown) => { setForm((current) => ({ ...current, [key]: value })); setState("dirty"); };
  useEffect(() => { if (!authToken || create) return; void fetch(endpoint, { headers: { Authorization: `Bearer ${authToken}` } }).then((r) => r.json()).then((data) => setForm({ ...empty, ...data.line, media: (data.line.media ?? []).map((item: Row) => ({ assetId: item.assetId, role: item.role, sortOrder: item.sortOrder })) })); }, [authToken, create, endpoint]);
  async function save() { setState("saving"); const payload = { ...form, createdAt: undefined, updatedAt: undefined, _count: undefined }; const response = await fetch(endpoint, { method: create ? "POST" : "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${authToken}`, ...(!create && form.updatedAt ? { "If-Match": form.updatedAt } : {}) }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setState(response.status === 409 ? "conflict" : "dirty"); return setMessage(data.error || JSON.stringify(data.fields)); } setForm((current) => ({ ...current, ...data.line })); setState("saved"); if (create) router.replace(`/admin/linhas/${data.line.id}`); }
  async function publicationAction(action: "publish" | "archive") { if (!form.id) return; const response = await fetch(`/api/admin/catalog/lines/${form.id}/${action}`, { method: "POST", headers: { Authorization: `Bearer ${authToken}` } }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setForm((current) => ({ ...current, status: data.line.status })); }
  const mediaFor = (role: string) => form.media.find((item: Row) => item.role === role)?.assetId ?? ""; const setMedia = (role: string, assetId: string) => change("media", [...form.media.filter((item: Row) => item.role !== role), ...(assetId ? [{ role, assetId, sortOrder: 0 }] : [])]);
  return <section className="max-w-5xl"><p className="font-mono text-xs uppercase tracking-wider text-accent">Marcas</p><h1 className="mt-1 font-display text-3xl font-semibold">{create ? "Nova marca" : `Editar ${form.name || "marca"}`}</h1><div className="mt-7 rounded-[24px] border border-content/10 bg-card"><AdminTabs tabs={tabs} active={tab} onChange={setTab} /><div className="p-5 md:p-7">
    {tab === "Identidade" ? <div className="grid gap-5 md:grid-cols-2"><AdminField label="Nome da marca"><input className={inputClass} value={form.name} onChange={(e) => { change("name", e.target.value); if (!form.id) change("slug", toSlug(e.target.value)); }} /></AdminField><AdminField label="Descritor" hint="Frase de uma linha que define a marca"><input className={inputClass} value={form.descriptor} onChange={(e) => change("descriptor", e.target.value)} /></AdminField><div className="md:col-span-2"><AdminField label="Frase de apresentação" hint="Texto de abertura da página da marca"><textarea className={inputClass} rows={4} value={form.tagline} onChange={(e) => change("tagline", e.target.value)} /></AdminField></div></div> : null}
    {tab === "Cores" ? <div className="grid gap-6 lg:grid-cols-2"><div className="grid gap-4 sm:grid-cols-2">{[["Superfície clara", "surfaceLight"], ["Superfície escura", "surfaceDark"], ["Destaque claro", "accentLight"], ["Destaque escuro", "accentDark"], ["Texto claro", "inkLight"], ["Texto escuro", "inkDark"]].map(([label, key]) => <AdminField key={key} label={label}><div className="flex gap-2"><input type="color" value={form[key]} onChange={(e) => change(key, e.target.value)} className="h-11 w-14 rounded-lg border border-content/10 bg-transparent" /><input className={inputClass} value={form[key]} onChange={(e) => change(key, e.target.value)} /></div></AdminField>)}</div><div className="space-y-4"><Preview form={form} dark={false} /><Preview form={form} dark /></div></div> : null}
    {tab === "Institucional" ? <div className="space-y-5">{[["Missão", "mission"], ["Visão", "vision"], ["Valores", "values"]].map(([label, key]) => <AdminField key={key} label={label}><textarea rows={3} className={inputClass} value={form[key] ?? ""} onChange={(e) => change(key, e.target.value)} /></AdminField>)}<AdminField label="Diferenciais" hint="Um por linha"><textarea rows={6} className={inputClass} value={form.differentials.join("\n")} onChange={(e) => change("differentials", e.target.value.split("\n").filter(Boolean))} /></AdminField><AdminField label="Compromissos" hint="Um por linha"><textarea rows={5} className={inputClass} value={form.commitments.join("\n")} onChange={(e) => change("commitments", e.target.value.split("\n").filter(Boolean))} /></AdminField></div> : null}
    {tab === "Fotos" ? <div className="grid gap-5 md:grid-cols-3"><MediaPicker defaults={{ category: "BRAND", lineId: form.id }} label="Logo" hint="Marca em fundo transparente" value={mediaFor("LOGO")} onChange={(value) => setMedia("LOGO", value)} /><MediaPicker defaults={{ category: "BRAND", lineId: form.id }} label="Imagem de destaque" hint="Foto grande do topo da página" value={mediaFor("HERO")} onChange={(value) => setMedia("HERO", value)} /><MediaPicker defaults={{ category: "BRAND", lineId: form.id }} label="Banner" hint="Faixa larga, opcional" value={mediaFor("BANNER")} onChange={(value) => setMedia("BANNER", value)} /></div> : null}
    {tab === "Publicação" ? <div className="space-y-5"><AdminField label="Ordem"><input type="number" className={inputClass} value={form.sortOrder} onChange={(e) => change("sortOrder", Number(e.target.value))} /></AdminField><p>Status: <strong>{form.status}</strong></p><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-content/50">Endereço no site</p><p className="mt-1 font-mono text-xs text-content/60">/linhas/{form.slug || "…"}</p>{form.slug ? <a href={`/linhas/${form.slug}`} target="_blank" className="mt-1 inline-block text-sm font-semibold text-accent">Abrir no site</a> : null}</div>{form.id ? <div className="flex gap-2"><button type="button" onClick={() => void publicationAction("publish")} className="rounded-full bg-action px-5 py-2 text-sm font-semibold text-action-fg">Publicar</button><button type="button" onClick={() => void publicationAction("archive")} className="rounded-full border border-content/15 px-5 py-2 text-sm font-semibold">Arquivar</button></div> : null}</div> : null}
  </div></div>{message ? <p className="mt-4 rounded-xl bg-raised p-3 text-sm">{message}</p> : null}<SaveBar state={state} onSave={() => void save()} onPublish={form.id ? () => void publicationAction("publish") : undefined} /></section>;
}
function Preview({ form, dark }: { form: Row; dark: boolean }) { const background = dark ? form.surfaceDark : form.surfaceLight; const color = dark ? form.inkDark : form.inkLight; const accent = dark ? form.accentDark : form.accentLight; return <div className="rounded-[24px] p-5" style={{ background, color }}><p className="font-mono text-xs uppercase" style={{ color: accent }}>{dark ? "Tema escuro" : "Tema claro"}</p><h3 className="mt-2 font-display text-2xl font-semibold">{form.name || "Nome da marca"}</h3><p className="mt-2 text-sm opacity-75">{form.tagline || "Frase de apresentação"}</p><button type="button" className="mt-5 rounded-full px-4 py-2 text-xs font-semibold" style={{ background: accent, color: background }}>Explorar</button></div>; }
