import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/adminGuard";
import { prisma } from "@/lib/prisma";
import { audit, requireUnchanged, validationError } from "@/server/admin/mutation";
const schema = z.object({ id: z.string().uuid().optional(), scope: z.enum(["GLOBAL", "LINE"]), lineId: z.string().uuid().nullish(), question: z.string().min(2), answer: z.string().min(2), links: z.array(z.object({ href: z.string(), label: z.string() })).default([]), isPublished: z.boolean().default(false), sortOrder: z.number().int().default(0) }).refine((data) => (data.scope === "GLOBAL") === !data.lineId, "Escopo e linha incompatíveis.");
export async function GET(req: Request) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; return NextResponse.json({ items: await prisma.faqItem.findMany({ orderBy: { sortOrder: "asc" } }) }); }
export async function POST(req: Request) { return save(req, false); } export async function PATCH(req: Request) { return save(req, true); }
async function save(req: Request, update: boolean) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const parsed = schema.safeParse(await req.json()); if (!parsed.success) return NextResponse.json(validationError(parsed.error), { status: 400 }); const { id, ...data } = parsed.data; if (update && !id) return NextResponse.json({ error: "ID obrigatório." }, { status: 400 }); if (update) { const before = await prisma.faqItem.findUnique({ where: { id } }); if (!before) return NextResponse.json({ error: "FAQ não encontrado." }, { status: 404 }); const stale = requireUnchanged(req, before.updatedAt); if (stale) return stale; } const item = update ? await prisma.faqItem.update({ where: { id }, data }) : await prisma.faqItem.create({ data }); await audit(admin.user.userId, "FaqItem", item.id, update ? "update" : "create", data); return NextResponse.json({ item }, { status: update ? 200 : 201 }); }
export async function DELETE(req: Request) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const id = new URL(req.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "ID obrigatório." }, { status: 400 }); await prisma.faqItem.delete({ where: { id } }); await audit(admin.user.userId, "FaqItem", id, "delete", {}); return NextResponse.json({ success: true }); }
