import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/adminGuard";
import { prisma } from "@/lib/prisma";
import { linePatchSchema } from "@/lib/validation/catalog";
import { audit, requireUnchanged, validationError } from "@/server/admin/mutation";
type Context = { params: Promise<{ id: string }> };
export async function GET(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const line = await prisma.line.findUnique({ where: { id: (await params).id }, include: { media: { include: { asset: true } } } }); return line ? NextResponse.json({ line }) : NextResponse.json({ error: "Linha não encontrada." }, { status: 404 }); }
export async function PATCH(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const parsed = linePatchSchema.safeParse(await req.json()); if (!parsed.success) return NextResponse.json(validationError(parsed.error), { status: 400 }); const id = (await params).id; const before = await prisma.line.findUnique({ where: { id } }); if (!before) return NextResponse.json({ error: "Linha não encontrada." }, { status: 404 }); const stale = requireUnchanged(req, before.updatedAt); if (stale) return stale; const { media, ...data } = parsed.data; const line = await prisma.$transaction(async (tx) => { if (media) { await tx.lineMedia.deleteMany({ where: { lineId: id } }); if (media.length) await tx.lineMedia.createMany({ data: media.map((item) => ({ ...item, lineId: id })) }); } return tx.line.update({ where: { id }, data, include: { media: { include: { asset: true } } } }); }); await audit(admin.user.userId, "Line", id, "update", { before, after: line }); return NextResponse.json({ line }); }
export async function DELETE(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const id = (await params).id; const dependencies = await prisma.line.findUnique({ where: { id }, include: { _count: { select: { products: true, protocols: true, cases: true } } } }); if (!dependencies) return NextResponse.json({ error: "Linha não encontrada." }, { status: 404 }); if (dependencies._count.products || dependencies._count.protocols || dependencies._count.cases) { const line = await prisma.line.update({ where: { id }, data: { status: "ARCHIVED" } }); await audit(admin.user.userId, "Line", id, "archive", dependencies._count); return NextResponse.json({ line, archived: true }); } await prisma.line.delete({ where: { id } }); await audit(admin.user.userId, "Line", id, "delete", {}); return NextResponse.json({ success: true }); }
