import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/adminGuard";
import { prisma } from "@/lib/prisma";
import { productPatchSchema } from "@/lib/validation/catalog";
import { audit, validationError } from "@/server/admin/mutation";
import { productInclude } from "@/server/catalog/mappers";
type Context = { params: Promise<{ id: string }> };
export async function GET(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const product = await prisma.product.findUnique({ where: { id: (await params).id }, include: productInclude }); return product ? NextResponse.json({ product }) : NextResponse.json({ error: "Produto não encontrado." }, { status: 404 }); }
export async function PATCH(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const parsed = productPatchSchema.safeParse(await req.json()); if (!parsed.success) return NextResponse.json(validationError(parsed.error), { status: 400 }); const id = (await params).id; const before = await prisma.product.findUnique({ where: { id } }); if (!before) return NextResponse.json({ error: "Produto não encontrado." }, { status: 404 }); const expected = req.headers.get("if-match"); if (!expected) return NextResponse.json({ error: "If-Match é obrigatório." }, { status: 428 }); if (expected !== before.updatedAt.toISOString()) return NextResponse.json({ error: "Este produto foi alterado por outra pessoa." }, { status: 409 }); const product = await prisma.$transaction(async (tx) => { if (parsed.data.slug && parsed.data.slug !== before.slug && before.status !== "DRAFT") await tx.slugRedirect.upsert({ where: { fromPath: `/produtos/${before.slug}` }, update: { toPath: `/produtos/${parsed.data.slug}` }, create: { fromPath: `/produtos/${before.slug}`, toPath: `/produtos/${parsed.data.slug}` } }); return tx.product.update({ where: { id }, data: parsed.data }); }); await audit(admin.user.userId, "Product", id, "update", { before, after: product }); return NextResponse.json({ product }); }
