import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/adminGuard";
import { prisma } from "@/lib/prisma";
import { skuPatchSchema } from "@/lib/validation/catalog";
import { audit, requireUnchanged, validationError } from "@/server/admin/mutation";
type Context = { params: Promise<{ id: string; skuId: string }> };
const PROTECTED_ALIASES = new Set(["enz-slim", "enz-smooth", "enz-drain", "enz-slim-plus", "enz-smooth-plus", "enz-drain-plus"]);
export async function PATCH(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const parsed = skuPatchSchema.safeParse(await req.json()); if (!parsed.success) return NextResponse.json(validationError(parsed.error), { status: 400 }); const { id, skuId } = await params; const before = await prisma.sku.findFirst({ where: { id: skuId, productId: id }, include: { aliases: true } }); if (!before) return NextResponse.json({ error: "SKU não encontrado." }, { status: 404 }); const stale = requireUnchanged(req, before.updatedAt); if (stale) return stale; const { aliases, ...data } = parsed.data; if (aliases) { const removed = before.aliases.map((item) => item.alias).filter((alias) => !aliases.includes(alias)); const inOrders = await prisma.orderItem.count({ where: { productId: { in: removed } } }); if (inOrders || removed.some((alias) => PROTECTED_ALIASES.has(alias))) return NextResponse.json({ error: "Um apelido histórico ou em uso não pode ser removido." }, { status: 409 }); } const sku = await prisma.$transaction(async (tx) => { if (aliases) { await tx.skuAlias.deleteMany({ where: { skuId } }); if (aliases.length) await tx.skuAlias.createMany({ data: aliases.map((alias) => ({ alias, skuId })) }); } return tx.sku.update({ where: { id: skuId }, data, include: { aliases: true } }); }); await audit(admin.user.userId, "Sku", skuId, "update", { before, after: sku }); return NextResponse.json({ sku }); }
export async function DELETE(req: Request, { params }: Context) { const admin = await requireAdmin(req); if (!admin.ok) return admin.response; const { id, skuId } = await params; const sku = await prisma.sku.findFirst({ where: { id: skuId, productId: id }, include: { aliases: true } }); if (!sku) return NextResponse.json({ error: "SKU não encontrado." }, { status: 404 }); const identifiers = [sku.code, ...sku.aliases.map((alias) => alias.alias)]; const sold = await prisma.orderItem.count({ where: { productId: { in: identifiers } } }); if (sold || sku.aliases.some((alias) => PROTECTED_ALIASES.has(alias.alias))) { const archived = await prisma.sku.update({ where: { id: skuId }, data: { isActive: false } }); await audit(admin.user.userId, "Sku", skuId, "archive", { code: sku.code }); return NextResponse.json({ success: true, archived: true, sku: archived }); } await prisma.skuAlias.deleteMany({ where: { skuId } }); await prisma.sku.delete({ where: { id: skuId } }); await audit(admin.user.userId, "Sku", skuId, "delete", { code: sku.code }); return NextResponse.json({ success: true, archived: false }); }
